### PR TITLE
espafiles: new module

### PR DESCRIPTION
**Pull request by dataoscar**
Supports:
- download anonymous
- probe for %f %s %i

### CODE REVIEW

**Comment by Raziel-23** [comment]
Quick suggestion, you wrote this module, so in the copyright statement there should be your credits, not mine :smirk:

**Comment by dataoscar** [comment]
Hehe, sorry I did a copy and paste from another module. I will change it.

**Comment by Raziel-23** [comment]
Now you removed too much. Every module contains information how they can be distributed (GPL version 3). A copyright line like mine '# Copyright (c) 2016 Raziel-23' only indicates who wrote a particular module. You should leave those 3 lines and change only the copyright line. You can do this like I did and change only my nickname to yours, or you can write something similar like [here](https://github.com/mcrapet/plowshare-modules-legacy/pull/60/files#diff-f15032998b529162838a58cbbe06b40fR2).

**Comment by dataoscar** [comment]
Sorry for the delay. Added the new line.

Thanks for being patient.

**Comment by mcrapet** [comment]
You probably mean:
`MODULE_ESPAFILES_REGEXP_URL='https\?://\(www\.\)\?espafiles\.com/'`
Instead of:
`MODULE_ESPAFILES_REGEXP_URL='http\?://\(www\.\)\?espafiles\.com/'`

**Comment by Raziel-23** [comment]
Please Matthieu wait before merging this PR, because it doesn't work properly. It downloads a html page instead of a real file. I didn't check this earlier. I know what is wrong. The cause is an unusual redirection. I will prepare what it must be changed.

**Comment by Raziel-23** [comment]
Here are changes:
https://github.com/Raziel-23/plowshare-modules-legacy/commit/80ebf4761fe3244464c174ea6d8322c08114cb34
Please improve your PR and squash commits and leave the first commit message. If you don't know how to squash [here it is instruction](https://github.com/mcrapet/plowshare-modules-legacy/pull/64#issuecomment-194131394).

**Comment by mcrapet** [comment]
@Raziel-23 : I let you handle this ;)

**Comment by Raziel-23** [comment]
@dataoscar One more thing, this service support resume downloads, so there should be:
```
MODULE_ESPAFILES_DOWNLOAD_RESUME=yes
```

**Comment by dataoscar** [comment]
I definitely know how to squash, will do that. I tested downloading before submitting, I will look again. IT could be that something has changed since then.

**Comment by dataoscar** [comment]
Question: How did you figure out they supported resume downloads?

**Comment by dataoscar** [comment]
```
$:/download# plowdown http://espafiles.com/f/IyytY  && md5sum "Test file 5MiB.zip"
Output directory: /download
Starting download (espafiles): http://espafiles.com/f/IyytY
File URL: http://espafiles.com/download/4mokPjo8fD1Te0gkeDAEpFt8fD12piSWp0YueDYueDj8fDbXeDjFYasae0ITeFYwY2Y2J0hXpDtiJDRatFPoe2ti_e2a5f6bb483d83191a47413b99546831/Test%20file%205MiB.zip
Filename: Test file 5MiB.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5120k  100 5120k    0     0   481k      0  0:00:10  0:00:10 --:--:--  645k
/download/Test file 5MiB.zip
277a797522f04863da321f962d7afd2b  Test file 5MiB.zip
```

Now with resume support

```
$:/download# plowdown http://espafiles.com/f/IyytY  && md5sum "Test file 5MiB.zip"
Output directory: /download
Starting download (espafiles): http://espafiles.com/f/IyytY
File URL: http://espafiles.com/download/4mokPjo8fD1Te0gkeDA3p0O8fD12piSWp0YueDYueDj8fDgaY0swpyOotF5kYas3e2pWJ0ASYX1aeXI3JD5wtyYE_437db182f92dc82c37f00331ea817754/Test%20file%205MiB.zip
Filename: Test file 5MiB.zip
** Resuming transfer from byte position 12288
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5108k  100 5108k    0     0   537k      0  0:00:09  0:00:09 --:--:--  557k
/download/Test file 5MiB.zip
277a797522f04863da321f962d7afd2b  Test file 5MiB.zip
```

**Comment by Raziel-23** [comment]
Ok, it works now. In plowprobe file identifier it is not the whole url. There are also a few cosmetic changes (like redundant spaces) and resume download set to no:
https://github.com/Raziel-23/plowshare-modules-legacy/commit/3bb440754190b3536e00825295fdfe675207615e

Strange, yesterday resume downloads worked for me, but today they don't. Do you work for them and change this? Just kidding :D. They changed it during the night. So yes you're right, they don't support resume downloads.

Test is pretty simply. I download only part of a file (during download press Ctrl-C) and try download it again. If curl finish download properly and there is no error, then I know that this service support resume downloads. I know that 5MiB file is very small to do that, but when press fast Ctrl-C during downloading, then you can check it.

**Comment by dataoscar** [comment]
Hehe, yeah pretty odd behavior. Resume downloads were working for me. I tested the functionality as you described, don't really know whats going on.

**Comment by Raziel-23** [comment]
Ok, it is better to assume they don't support resume downloading. Can you correct your PR as with changes that I made here:
https://github.com/Raziel-23/plowshare-modules-legacy/commit/3bb440754190b3536e00825295fdfe675207615e
or you prefer that I do this?

**Comment by dataoscar** [comment]
Changes applied. Thanks!

**Comment by Raziel-23** [comment]
Finally I can merge this PR! Thank you for your contribution!

**Pull request merged**
