### PR TITLE
keep2share: fix save with correct filename with paid account

### PR DESCRIPTION
**Pull request by dpeddi**

### CODE REVIEW

**Comment by Raziel-23** [comment]
Your fix doesn't work with such links:
```
http://k2s.cc/file/4d4fa3125b91a
```

Can you give an example of such filenames? What filenames you expect, and what filenames you get now?

BTW. May I have a favor? Could you run this script with your login and password for keep2share:
```
$ ./k2p_api.sh 'login' 'password'
```

```
#!/bin/bash

JSON=$(curl -s --data '{"username":"'"$1"'","password":"'"$2"'"}' 'http://keep2share.cc/api/v2/login')
JSON="${JSON:1:${#JSON}-2}"
IFS=':' read -r _ _ _ TOKEN <<< "$JSON"

TOKEN="${TOKEN:1:${#TOKEN}-2}"
JSON=$(curl -s --data '{"auth_token": "'$TOKEN'"}' 'http://keep2share.cc/api/v2/accountInfo')
echo "$JSON"
```
and give the output of it. I just want to know if in this way I can check if this is a premium account.

**Comment by dpeddi** [comment]
Ooops, yes I confirm so...

dbg: plowdown: --no-overwrite selected
WARNING: Wrong configuration file permissions. Fix it with: chmod 600
/root/.config/plowshare/plowshare.conf
keep2share: take --auth option from configuration file
Starting download (keep2share): http://k2s.cc/file/4d4fa3125b91a
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
 Current
                                 Dload  Upload   Total   Spent    Left
 Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
  0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
 Current
                                 Dload  Upload   Total   Spent    Left
 Speed
100   147    0    94  100    53    282    159 --:--:-- --:--:-- --:--:--
283
dbg: Successfully logged in as eddi@depieri.net member
dbg: storage_set: `token' set for module `keep2share'
dbg: token: 'crih6rsj86h6efclkuv208sfagr1j309'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
 Current
                                 Dload  Upload   Total   Spent    Left
 Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
  0
File URL:
http://prx-116.keep2share.cc/a1b6774ed5126/b8f558d57ed3f/da44b83d9a59c?temp_url_sig=7f0451f74acc7b3151a798cf4640b4a0106a926e21a1cb721001e7b883f7e19553297d3c40b56f0954f59118e380ba9f45d6383241d6f467fa1d9482bb6b913b&temp_url_expires=1458315324&id=99997d39ad477&node_id=116&project=moneyplatform&user_id=891559&name=Test+file+5MB.zip
Filename: da44b83d9a59c
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
 Current
                                 Dload  Upload   Total   Spent    Left
 Speed
100 5120k  100 5120k    0     0   324k      0  0:00:15  0:00:15 --:--:--
 337k
da44b83d9a59c

**Comment by dpeddi** [comment]
before logging on my profile from a browser
root@proliant:/data/stb/divxxx/bin# sh k2p_api.sh dp**@****** *******
{"message":"No allow from this
network","status":"error","code":403,"errorCode":73}
root@proliant:/data/stb/divxxx/bin# sh  -x k2p_api.sh dp**@****** *******
++ curl -s --data '{"username":"dp**@******","password":"*******"}'
http://keep2share.cc/api/v2/login
+
JSON='{"status":"success","code":200,"auth_token":"crih6rsj86h6efclkuv208sfagr1j309"}'
+
JSON='"status":"success","code":200,"auth_token":"crih6rsj86h6efclkuv208sfagr1j309"'
+ IFS=:
+ read -r _ _ _ TOKEN
+ TOKEN=crih6rsj86h6efclkuv208sfagr1j309
++ curl -s --data '{"auth_token": "crih6rsj86h6efclkuv208sfagr1j309"}'
http://keep2share.cc/api/v2/accountInfo
+ JSON='{"message":"No allow from this
network","status":"error","code":403,"errorCode":73}'
+ echo '{"message":"No allow from this
network","status":"error","code":403,"errorCode":73}'

after logging in from my browser
{"message":"No allow from this
network","status":"error","code":403,"errorCode":73}
root@proliant:/data/stb/divxxx/bin# sh  -x k2p_api.sh dp**@****** *******
++ curl -s --data '{"username":"dp**@******","password":"*******"}'
http://keep2share.cc/api/v2/login
+
JSON='{"status":"success","code":200,"auth_token":"crih6rsj86h6efclkuv208sfagr1j309"}'
+
JSON='"status":"success","code":200,"auth_token":"crih6rsj86h6efclkuv208sfagr1j309"'
+ IFS=:
+ read -r _ _ _ TOKEN
+ TOKEN=crih6rsj86h6efclkuv208sfagr1j309
++ curl -s --data '{"auth_token": "crih6rsj86h6efclkuv208sfagr1j309"}'
http://keep2share.cc/api/v2/accountInfo
+
JSON='{"status":"success","code":200,"available_traffic":21474836480,"account_expires":1460505600}'
+ echo
'{"status":"success","code":200,"available_traffic":21474836480,"account_expires":1460505600}'
{"status":"success","code":200,"available_traffic":21474836480,"account_expires":1460505600}

**Comment by Raziel-23** [comment]
Thank you for testing this script. Just as I thought, for free accounts they aren't set account_expires field, but for premium accounts they do.

Ok back to your problem, can you give me an example of filenames, what filenames you expect?

**Comment by dpeddi** [comment]
on a browser I get:


   1. Remote Address:
      88.85.73.233:80
      2. Request URL:

      http://prx-116.keep2share.cc/a1b6774ed5126/b8f558d57ed3f/da44b83d9a59c?temp_url_sig=7f0451f74acc7b3151a798cf4640b4a0106a926e21a1cb721001e7b883f7e19553297d3c40b56f0954f59118e380ba9f45d6383241d6f467fa1d9482bb6b913b&temp_url_expires=1458315324&id=99997d39ad477&node_id=116&project=moneyplatform&user_id=891559&name=Test+file+5MB.zip
      3. Request Method:
      GET
      4. Status Code:
      200 OK
      1. Response Headersview source
      1. Accept-Ranges:
      bytes
      2. Connection:
      keep-alive
      3. Content-Disposition:
      attachment; filename="Test file 5MB.zip";
      filename*=UTF-8''Test%20file%205MB.zip
      4. Content-Length:
      5242880
      5. Content-Type:
      application/octet-stream
      6. Date:
      Wed, 16 Mar 2016 16:31:30 GMT
      7. Etag:
      277a797522f04863da321f962d7afd2b
      8. Last-Modified:
      Tue, 26 Jan 2016 07:11:39 GMT
      9. Server:
      nginx/1.4.6 (Ubuntu)
      10. X-Timestamp:
      1453792298.58339
      11. X-Trans-Id:
      txad019369eac04d38a3971-0056e98a62


but on plowdown it seems that the content type isn't text-html, so the
content-disposition fail and don't answer for filename... My intention was
to parse the redirected uri string and parse name=, but perhaps isn't the
correct solution.

**Comment by Raziel-23** [comment]
I'm trying to figure out how to get filename from the official keep2share api:
https://github.com/keep2share/api
But it always fails for me with this error message: `"Invalid request params"`. I don't know, I will have to think.

**Comment by Raziel-23** [comment]
Finally this api worked for me. I will prepare fix based on api.

**Comment by Raziel-23** [comment]
Please test this version:
https://github.com/Raziel-23/plowshare-modules-legacy/commit/4b94aeb91d378670d565194092542c826df19a1c
If it will be working for you then I will push it to the master.

**Comment by dpeddi** [comment]
It works correctly!

Thank you!

**Comment by Raziel-23** [comment]
It's now in the master branch.

**Pull request closed without merging**
