### PR TITLE
1fichier (upload): replace [ and ] with compliant form for match and parse function

### PR DESCRIPTION
**Pull request by kidburglar**
Hello again ^^

If we try to upload a file with a folder that contain a "[" or "]" we have an error with the parse function.

To avoid the problem I replace this with '\[' and '\]' so it work with the match and parse function.

Cheers.

### CODE REVIEW

**Comment by Raziel-23** [comment]
Instead of `replace` there should be `replace_all`. In this way such directory names will work: `[[[Dir]]]`.

BTW. How many times we will improve one function? Just kidding :smile:. If you correct this then I will merge it.

**Comment by Raziel-23** [comment]
I don't know if you know, but I will give you one git tip. If you want improve a top commit then do this:
```
$ git add 1fichier
$ git commit --amend
$ git push -f
```
In this way you don't have to squash commits.

**Comment by kidburglar** [comment]
Thanks for the git tip.

It's a friend that saw this problem ^^
I did the commit --amend so it must be good now.

**Comment by Raziel-23** [comment]
Great. Thank you for your contribution and collaboration!

**Pull request merged**
