### PR TITLE
openload.io: new module

### PR DESCRIPTION
**Pull request by ljsdoug**
Anonymous download and probe support.

### CODE REVIEW

**Comment by ljsdoug** [comment]
A module I've written for personal use that I thought someone else might find useful.

I didn't know what the right way of writing the license header was, as I'm just a contributor. I merely left it at "Copyright (c) 2015 Plowshare team" even if I'm the author.

probe has file size support, but openload.io writes 1MiB as 1MB. translate_size_bin does this translation, but it's not as accurate as it possibly can be, because it's supposed to multiply the fractional part by 1024, not by 1000. The error is a few small KB, but if the behavior in core.sh isn't what was intended, it could be a bug? I didn't dare touch the translate_size implementation as other sites depend on it.

This is my first time writing a plowshare module, and the first time I wrote anything other than a few bash one liners. I hope the bash hackers here can review the code and see if I've done it correctly. To the best of my knowledge it handles the cases mentioned in the documentation and I've tested both download and probe on various links I've found of that site. 

I never had an account or the need to upload on openload.io, so support for that isn't written yet.

**Comment by mcrapet** [comment]
Hi,
Please could you send a v2 with:

1. Put your own copyright not Plowshare Team.
`Copyright (c) 2015 ljsdoug <x@y.z>`

2. Drop translate_size_bin()
It's now fixed in core. Thanks for notifying it!

3. Be carefull with globals:
replace:
`MODULE_OPENLOAD_IO_OPTIONS=""`
with
`MODULE_OPENLOAD_IO_DOWNLOAD_OPTIONS=""`
Add also missing:
`MODULE_OPENLOAD_IO_PROBE_OPTIONS=""`

4. Concerning regexp
You should accept both http and https:
`MODULE_OPENLOAD_IO_REGEXP_URL='https?://openload\.io/'`

**Comment by ljsdoug** [comment]
Changed copyright, dropped translate_size_bin, fixed options globals, added support for HTTP. 

I removed the old commit this pull request was based on, but if you want to see the difference, that has the original commit and the fixes, without being squashed into one commit, I've put those into a branch: https://github.com/ljsdoug/plowshare-modules-legacy/commits/openload_io_module

On the fixes:
The site never generates HTTP links, that's why I didn't add support for it the first time around. When you go to a HTTP link, it redirects you to a HTTPS one using the Location header. To allow support for HTTP, I've changed the curl calls to have a -L argument.

I removed translate_size_bin, replacing it with translate_size, but I'm not sure it works correctly for this site:
When this site says 1.5MB, it means 1.5*1024*1024bytes = 1572864 bytes.
translate_size would return 1.5 * 1000 * 1000 = 1500000 bytes.
What translate_size_bin did was convert the KB/MB/GB strings to KiB/MiB/GiB, which should be multiples of 1024. I can leave this part to be fixed in core, but if other sites depend on MB being in units of 1000, some other module could be broken by fixing the conversion for this site.

**Comment by mcrapet** [comment]
```
        # megabyte (10^6)
        M|MB)
            echo $(( 1000000 * R + 1000 * F))
            ;;
        # mebibyte (MiB)
        MiB|Mi|m|mB)
           echo $(( 1048576 * R + 1048576 * F / 1000))
            ;;
```

M is 1000^2, m is 1024^2, but K is 1024 and k is 1000. A lot of sites are doing wrong.

**Pull request merged**
