### PR TITLE
rapidgator.sh: module update

### PR DESCRIPTION
**Pull request by dyskette**
This request addreses the issues of #166 (download) and #168 (upload), also fixes the delete function.

### CODE REVIEW

**Comment by apemanzilla** [comment]
Any update on this? The fix works perfectly for me...

**Comment by mcrapet** [comment]
I applied #175. But I think I've missed the "delete" patch, could you resubmit it as standalone?
Thanks.

**Comment by dyskette** [comment]
Uh... OK.

It seems like @idleloop-github just took one commit from this pull request though. So I'm going to create a pull request with the upload and delete thing in one commit.

**Comment by rlsblogse** [comment]
hi,
again upload fail look like they again update http or https protocol

parse failed (sed): "/var form_url/ s/^.setProtocol("(.+)");.$/\1/p" (skip 0)

regards
bye

**Pull request closed without merging**
