### PR TITLE
upload.cd: added download and "cfsi" probe support for upload.cd

### PR DESCRIPTION
**Pull request by idleloop-github**

### CODE REVIEW

**Comment by mcrapet** [comment]
Hi
You forget to clean up `MODULE_UPLOAD_CD_DOWNLOAD_OPTIONS`
auth-free will appear in long help message and it is not (yet) supported.

**Comment by idleloop-github** [comment]
ok !

**Comment by idleloop-github** [comment]
I've patched an incorrect behaviour. Good merge is this last one (d1181a2),

**Comment by mcrapet** [comment]
Applied. Thanks again!

**Pull request merged**
