### PR TITLE
fix 1fichier.com

### PR DESCRIPTION
**Pull request by titusadn**
Here is just a little fix for 1fichier.com which wasn't working for a while

### CODE REVIEW

**Comment by greg-FR13** [comment]
Hi,
Thanks for the fix ; but it seems not working. Could you please check if it is ok for you ?
G

**Comment by titidude** [comment]
> Hi,
> Thanks for the fix ; but it seems not working. Could you please check if it is ok for you ?
> G

Hi, I'll check that within a few days

**Comment by albaldi** [comment]
tested today and it worked flawless 

```
$ plowdown https://1fichier.com/?xxxxxxxxx
Starting download (1fichier): https://1fichier.com/?xxxxxxx
File URL: https://o-5.1fichier.com/c120845970
Filename: xxxxxxxx.rar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2200M  100 2200M    0     0  4997k      0  0:07:30  0:07:30 --:--:-- 5820k
xxxxxxxxx.rar
```

**Comment by titidude** [comment]
I'm often using it and it's working for me too

**Comment by Kcchouette** [comment]
ping @mcrapet

**Comment by mcrapet** [comment]
Hi,

What is this adzone stuff, I don't have it here.

**Comment by mcrapet** [comment]
See also commit 67efb5416956075f53d9284f931f423a4f554081

Is this PR still relevant?

**Comment by titidude** [comment]
I don't know if this pull request is still relevent now. 
This module was failling due to advertisements. (A redirection was needed)
The adzone thing was used to deal with that. 

I can't test it anymore so I don't know if 1fichier.com is still using this kind of redirection

**Comment by titusadn** [comment]
OK i've tested and this pull request isn't relevant anymore. The 1fichier module is working well ! Good job !

**Pull request closed without merging**
