### PR TITLE
catshare: various improvements

### PR DESCRIPTION
**Pull request by Raziel-23**
I improved catshare module a bit. If you want I can squash commits into one.

### CODE REVIEW

**Comment by Raziel-23** [comment]
I forget about one thing in this pull request. In the probe function I can check if link is dead or need permissions in the same way like I did in the download function. Otherwise it will always return $ERR_LINK_DEAD, which is not true. There is only one issue with this approach, probe functions does not support returning $ERR_LINK_NEED_PERMISSIONS like download functions. Theoretically I can return $ERR_LINK_NEED_PERMISSIONS in the probe function, but it not print message 'Insufficient permissions (private/premium link)' like in the download function.

**Comment by mcrapet** [comment]
Hi,
In your probe function you can actually return `$ERR_LINK_NEED_PERMISSIONS`.

It will print (-v3):
Link active (with permissions): http://...

Could fix this and create a v2 pull request ?

**Comment by Raziel-23** [comment]
@mcrapet I push new commit to this pull request that fix it. I didn't know that in -v3 it this message show up.

**Comment by mcrapet** [comment]
Merged, thanks a lot !

**Pull request merged**
