### PR TITLE
1fichier (upload): Create and upload in subfolders

### PR DESCRIPTION
**Pull request by kidburglar**
We can now create and upload subfolders.
Exemple --folder directory/subdirectory will create directory and subdirectory
if not exist and upload the file in subdirectory

I use echo "$NAME" | tr '/' '\n' to search the dir_id of each directory.
It's maybe possible with parse but I have difficult with regex.

Feel free to optimize, if it's possible.

Cheers.

### CODE REVIEW

**Comment by Raziel-23** [comment]
I checked your PR and it is good, but I change a bit. We don't use 'tr' command due to a [portability](https://github.com/mcrapet/plowshare/wiki/Modules#portability) reason. Furthermore your loop doesn't support directories with spaces. I changed that and also I added a debug information about '$DIR_ID'. Here are changes that I did on top of your PR commit:
https://github.com/Raziel-23/plowshare-modules-legacy/commit/95bdd5369b070721923a74b0a631d4953fce4a1d

Please improve your PR, then I will merge it.

**Comment by kidburglar** [comment]
Sorry I had some problems with the rebase... It must be good now.
Thanks for your improve I don't know the possibility with read -a

**Comment by Raziel-23** [comment]
Maybe you are confused, because you wrote in the commit message:
```
Implements and closes #65.
```
and information show up that this PR will be closed when this commit will be merged. I use this line in my commits, because for me it is convenient to close issues in such way, see [here](https://help.github.com/articles/closing-issues-via-commit-messages/). I only use it for issues. I don't if it will have an impact on a pull request, probably nothing bad will happen :smile:. Nevertheless please remove this line from your commit message.

**Comment by kidburglar** [comment]
It's remove.
Yes I did it because you write it in my previous PR.

Sorry for all these troubles.

**Comment by Raziel-23** [comment]
No problem. Thank you for your contribution and collaboration!

**Comment by Raziel-23** [comment]
I missed that yesterday , but this function can be further improved. You can remove check if directory name contains '/' at the begin or the end, because `IFS='/' read -a DIR_NAMES <<< "$NAME"` line will remove all '/'. There is only one downside with such conversion to an array. If a directory name contains multiple consecutive '/' characters, then in the array we will have empty names. We can deal with this by skipping them in the loop. In this way the following directory name is valid and will be created properly:

```
--folder='///Dir - 1////Dir - 10////Dir - 100////'
```

Here are changes:
https://github.com/Raziel-23/plowshare-modules-legacy/commit/7ab975ee45399f25d0e5025fd4fd700deebbcb47

Please create new PR with those changes. I could commit it myself, but you develop almost everything in this aspect and I only improved it a bit. Unless you want me to do this.

**Comment by kidburglar** [comment]
You may commit it because I'm not have my computer before tomorrow.

**Comment by Raziel-23** [comment]
Done.

**Pull request merged**
