### PR TITLE
Fix #191 : uptobox : take into account a small ui changes

### LINKED ISSUE #191: UpToBox fails (16/02/18)
UpToBox fails to this date. Seems like they changed a few things.

> Hello,
> 
> we recently made some changes and technical updates.
> plowshare will certainly deliver an update to make them
> compatible again.
> May I suggest you to contact them directly to get further informations.
> 
> Thank you
> 
> Regards
> 
> 
> Philippe
> Uptobox support

### PR DESCRIPTION
**Pull request by coliss86**
Proof with a premium account : 
```
$ plowdown http://uptobox.com/5ptsfgkkk9ha
Output directory: /tmp
uptobox: take --auth option from configuration file
Starting download (uptobox): http://uptobox.com/5ptsfgkkk9ha
Starting login process: XXXXX/************
File URL: https://www90.uptobox.com/dl/AAafkqj_se8VeidpgybvCmYAkEfFpxxzb46Na0jFJd1XSs7r5506a_UW31mxXnIMOowFeUAflmRF8-ysWT6aZotjl24Rq6x9_v2iNzx3umRTPOZ019bbzBEi6Om-Qz6DSqDwuTpzeYviuBxMGtBNFQ/LICENSE
Filename: LICENSE
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 35147  100 35147    0     0   193k      0 --:--:-- --:--:-- --:--:--  193k
/tmp/LICENSE
```

### CODE REVIEW

**Comment by skillfr** [comment]
Merci mais cela ne fonctionne toujours pas.


dll@dll:~$ plowdown http://uptobox.com/5ptsfgkkk9ha
uptobox: take --auth option from configuration file
Starting download (uptobox): http://uptobox.com/5ptsfgkkk9ha
Starting login process: xxxx/**********
grep_form_by_name failed (sed): "name=F1"
Failed inside uptobox_download() [1]

**Comment by zodman** [comment]
I Confirm the PR, buts this PR needs #192  apply first

```
$ plowup uptobox  LICENSE  -a XXXXXX:XXXXXXXX
Starting upload (uptobox): LICENSE
Destination file: LICENSE
Starting login process: XXXXX/******
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 35602  100   157  100 35445    224  50624 --:--:-- --:--:-- --:--:-- 50635
#DEL http://uptobox.com/6m7mc5pzi1y8?killcode=604c0ddb80
http://uptobox.com/6m7mc5pzi1y8
```

**Comment by coliss86** [comment]
@skillfr : did you use a premium account ? 
@zodman : I didn't need #192 to download. Nevertheless, both should be merged at the end.

**Comment by skillfr** [comment]
@coliss86 yes I have a premium account
I took your file, so it should work

**Comment by zodman** [comment]
@coliss86  without my patch didnt work... only testing your patch ...

here my settings:

**Comment by skillfr** [comment]
@zodman for the upload but for the download I did not need to change the uptobox_upload() party it works without

**Comment by mcrapet** [comment]
Applied thanks.
You could use a more generic regexp next time: `[Pp]remium`

**Pull request merged**
