### PR TITLE
uptobox (download): update (upstream changed)

### PR DESCRIPTION
**Pull request by shahwahed**
fixing download for freeaccount #191 
havn't test on premium account as I havn't got one

### CODE REVIEW

**Comment by mcrapet** [comment]
Testers welcome here.

**Comment by shahwahed** [comment]
Have retested missing something when you have to wait have corrected it

**Comment by skillfr** [comment]
work 
nvidia share_2018-03-10_22-29-18

not work 
nvidia share_2018-03-10_22-30-15

```
#plowdown http://uptobox.com/5ptsfgkkk9ha
uptobox: take --auth option from configuration file
Starting download (uptobox): http://uptobox.com/5ptsfgkkk9ha
Starting login process: XXXX/**********
parse_attr failed (sed): "/<[Ii][Nn][Pp][Uu][Tt][^>]*name[[:space:]]*=[[:space:]]*["']\?waitingToken["']\?[[:space:]/>]/ value="
Failed inside parse_form_input_by_name(), line 1058, core.sh
Failed inside uptobox_download(), line 155, uptobox.sh
Failed inside uptobox_download() [1]
```

**Comment by shahwahed** [comment]
should work now
plowdown: force captcha method (imgur)
uptobox: take --auth option from configuration file
Starting download (uptobox): https://uptobox.com/******
Starting login process: ************/***********
Waiting 31 seconds... done         
File URL: http://www85.uptobox.com/dl/*****************************
Filename: *****************
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  926M  100  926M    0     0   306k      0  0:51:39  0:51:39 --:--:--  317k
link marked in file `toto.txt' (#OK)

**Comment by mcrapet** [comment]
Applied. Thanks for help guys!

**Comment by htiz** [comment]
Bravo guys and many thanks for your work on this !

**Pull request merged**
