### PR TITLE
fix uptobox upload

### PR DESCRIPTION
**Pull request by zodman**
fix the upload

### CODE REVIEW

**Comment by hriad** [comment]
`parse_json failed (json): "url"
Failed inside uptobox_upload(), line 297, uptobox.sh
parse_json failed (json): "deleteUrl"
Failed inside uptobox_upload(), line 298, uptobox.sh
Output URL expected`

**Comment by zodman** [comment]
@Cinpph  @hriad  test again put the -v 4 for more debugging  plz!

**Comment by Cinpph** [comment]
@zodman Ok for me with the last commit, good job !

**Comment by Cinpph** [comment]
I think that @hriad didn't update correctly its module.

**Comment by hriad** [comment]
@Cinpph The error I reported was just another symptom of the same issue your reported. Because the file was uploaded as anonymous, I did hit the max allowed file size and the upload got interrupted resulting into that error message.

@zodman Working great now. Good job!

**Comment by mcrapet** [comment]
Applied, thanks !

**Pull request merged**
