### PR TITLE
Update uptobox.sh

### PR DESCRIPTION
**Pull request by Ilgazil**
refs #135
Fixes the non premium waiting message

### CODE REVIEW

**Comment by mcrapet** [comment]
Hi,
Sorry I forgot to push my old fix.
See here b2307e7061616d03c2a8b1e2d1cd85e4290f0d00.
Could you retest? Thanks.

**Comment by Ilgazil** [comment]
Hi
Thanks, it's ok. Successfully tested (and currently running ^^)

See ya!

----- Mail original -----
De: "Matthieu Crapet" <notifications@github.com>
À: "mcrapet/plowshare-modules-legacy" <plowshare-modules-legacy@noreply.github.com>
Cc: "Thomas Vivien" <thomas.vivien@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Jeudi 10 Août 2017 14:09:01
Objet: Re: [mcrapet/plowshare-modules-legacy] Update uptobox.sh (#163)



Hi, 
Sorry I forgot to push my old fix. 
See here b2307e7 . 
Could you retest? Thanks.

**Comment by mcrapet** [comment]
Great, thanks!

**Comment by Ilgazil** [comment]
Hi!

In fact, it can be optimized with an hour handler.

Here is the complete message :
'You need a PREMIUM account to download new files immediatly without waiting, or you can wait 1 hour, 51 minutes, 46 seconds to launch a new download'

Your script does not handle the hours, so the internal wait of plowdown is based on the minutes. In the case above, the script will wait 51 minutes until next try, where we'll have to wait for 60 minutes.
I let you choose to handle this or not :)

Thanks for your work, by the way!

----- Mail original -----
De: "Matthieu Crapet" <notifications@github.com>
À: "mcrapet/plowshare-modules-legacy" <plowshare-modules-legacy@noreply.github.com>
Cc: "Thomas Vivien" <thomas.vivien@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Jeudi 10 Août 2017 14:09:01
Objet: Re: [mcrapet/plowshare-modules-legacy] Update uptobox.sh (#163)



Hi, 
Sorry I forgot to push my old fix. 
See here b2307e7 . 
Could you retest? Thanks.

**Comment by mcrapet** [comment]
I think I was too lazy to add hours parsing.. Your patch is welcome :)

**Pull request closed without merging**
